Box or Many apps together
Abdur-rahmaanJ/shopcube pull request #237
Opened 2021-01-03 09:39 UTC by Abdur-rahmaanJ

2021-01-03 09:40 UTC, pep8speaks commented
Hello @Abdur-rahmaanJ! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`shopyo/app.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/app.py):

> [Line 60:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/app.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 85:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/app.py#L85): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 86:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/app.py#L86): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 98:68](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/app.py#L98): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','









* In the file [`shopyo/modules/base/view.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/base/view.py):

> [Line 13:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/base/view.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)

* In the file [`shopyo/modules/category/models.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/models.py):

> [Line 15:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/models.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

* In the file [`shopyo/modules/category/test_category.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py):

> [Line 27:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 145:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L145): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 184:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L184): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 199:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L199): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 201:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L201): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 238:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L238): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 254:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L254): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 259:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L259): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 271:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L271): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 276:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L276): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 287:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L287): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 291:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/test_category.py#L291): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

* In the file [`shopyo/modules/category/view.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py):

> [Line 87:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L87): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 121:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L121): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 169:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L169): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 185:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L185): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 210:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L210): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 233:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L233): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 242:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L242): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 257:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L257): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 290:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L290): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 299:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L299): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 323:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L323): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 330:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L330): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 392:80](https://github.com/Abdur-rahmaanJ/shopyo/blob/3fcbaae3b251264b9adbc6c64ea13a2bd8c93b34/shopyo/modules/category/view.py#L392): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

* In the file [`shopyo/modules/contact/forms.py`](https://githu [...]

2021-01-03 09:50 UTC, Abdur-rahmaanJ commented
@rehmanis idk why travis tests failing

2021-01-03 11:16 UTC, rehmanis requested changes

2021-01-03 11:16 UTC, rehmanis commented on shopyo/conftest.py
> +
Looks like the merge messed up some things. This function should not be there according to my recent PR. Check and compare the conftest.py file here https://github.com/rehmanis/shopyo/blob/3afe2e14c978854239130cfeadea547b89582ff8/shopyo/conftest.py

2021-01-03 11:16 UTC, rehmanis commented on shopyo/modules/admin/test_user.py
> +
The removed changes(red ones) are the correct ones. Check the line 17 here https://github.com/rehmanis/shopyo/blob/3afe2e14c978854239130cfeadea547b89582ff8/shopyo/modules/admin/test_user.py

2021-01-03 11:16 UTC, rehmanis commented on shopyo/modules/category/test_category.py
> +    assert request.path == url_for("login.login")
The remove changes are the correct one. It missing one assert line 26  `assert response.status_code == 200`

2021-01-03 11:16 UTC, rehmanis commented on shopyo/conftest.py
>      yield session
This is also messed up.  Correct one is here https://github.com/rehmanis/shopyo/blob/3afe2e14c978854239130cfeadea547b89582ff8/shopyo/conftest.py

2021-01-03 11:19 UTC, rehmanis commented
> @rehmanis idk why travis tests failing

conftest.py file is modified incorrectly after merge. Test cases using are using old fixture `init_database` instead of `db`. I have pointed out the difference but might have missed some.

2021-01-03 11:32 UTC, Abdur-rahmaanJ commented
I wrongly updated after merging your PR

2021-01-03 12:27 UTC, Abdur-rahmaanJ commented
@rehmanis i just remerged your last branch (cherry-pick) into box, fixing the wrong ends on my part

2021-01-03 19:59 UTC, rehmanis commented
> @rehmanis i just remerged your last branch (cherry-pick) into box, fixing the wrong ends on my part

@Abdur-rahmaanJ looks like it is fine now.

2021-01-04 06:52 UTC, Abdur-rahmaanJ commented
@rehomanis i did not cherry-pick the mentionned commit.

2021-01-04 06:53 UTC, merged